//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('ReviewsAndRatings')
export class ReviewsAndRatingsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  reviewerId: number;

  @Column('real', { nullable: true })
  rating: number;

  @Column('text', { nullable: true })
  comments: string;

  @Column('date', { nullable: true })
  date: Date;

  @Column('date', { nullable: true })
  time: Date;
}
