//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const ReviewsAndRatingsTitle = () => {
  const record = useRecordContext();
  return (
    <span>ReviewsAndRatings {record ? `"${record.reviewerId}"` : ''}</span>
  );
};

export const ReviewsAndRatingsList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <ReferenceField source="reviewerId" reference="users" />
      <NumberField source="rating" />
      <TextField source="comments" />
      <DateField source="date" />
      <DateField source="time" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const ReviewsAndRatingsEdit = () => (
  <Edit title={<ReviewsAndRatingsTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="reviewerId" reference="users" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="rating" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="comments" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="date" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="time" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const ReviewsAndRatingsCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="reviewerId" reference="users" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="rating" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="comments" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="date" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="time" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  <ReferenceInput
    source="reviewerId"
    label="reviewerId"
    reference="users"
    alwaysOn
  />,
  ,
  ,
  ,
  ,
];
