//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="Share Car Trip - So Easy, No Wonder" />
    <CardContent>
      Share Car Trip: The smarter way to travel. Find rides with ease, save
      money on your commute, and reduce your environmental impact. Enjoy
      real-time ride tracking, secure payments, and a vibrant community of
      riders and drivers. Download the app and experience the future of
      carpooling!
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
