//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Rides: {
      name: 'Rides',
      fields: {
        destination: 'Destination',
        date: 'Date',
        time: 'Time',
        carType: 'Car Type',
        driverRating: 'Driver Rating',
        estimatedFare: 'Estimated Fare',
        id: 'id',
      },
    },
    Users: {
      name: 'Users',
      fields: {
        name: 'Name',
        contactDetails: 'Contact Details',
        paymentMethods: 'Payment Methods',
        id: 'id',
      },
    },
    Payments: {
      name: 'Payments',
      fields: {
        transactionId: 'Transaction Id',
        amount: 'Amount',
        paymentMethods: 'Payment Methods',
        payerIds: 'Payer Ids',
        paymentStatus: 'Payment Status',
        id: 'id',
      },
    },
    ReviewsAndRatings: {
      name: 'Reviews And Ratings',
      fields: {
        reviewerId: 'Reviewer Id',
        rating: 'Rating',
        comments: 'Comments',
        date: 'Date',
        time: 'Time',
        id: 'id',
      },
    },
    TripHistory: {
      name: 'Trip History',
      fields: {
        tripId: 'Trip Id',
        userId: 'User Id',
        tripDate: 'Trip Date',
        destination: 'Destination',
        status: 'Status',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Rides: {
      name: 'Rides (fr)',
      fields: {
        destination: 'Destination (fr)',
        date: 'Date (fr)',
        time: 'Time (fr)',
        carType: 'Car Type (fr)',
        driverRating: 'Driver Rating (fr)',
        estimatedFare: 'Estimated Fare (fr)',
        id: 'id',
      },
    },
    Users: {
      name: 'Users (fr)',
      fields: {
        name: 'Name (fr)',
        contactDetails: 'Contact Details (fr)',
        paymentMethods: 'Payment Methods (fr)',
        id: 'id',
      },
    },
    Payments: {
      name: 'Payments (fr)',
      fields: {
        transactionId: 'Transaction Id (fr)',
        amount: 'Amount (fr)',
        paymentMethods: 'Payment Methods (fr)',
        payerIds: 'Payer Ids (fr)',
        paymentStatus: 'Payment Status (fr)',
        id: 'id',
      },
    },
    ReviewsAndRatings: {
      name: 'Reviews And Ratings (fr)',
      fields: {
        reviewerId: 'Reviewer Id (fr)',
        rating: 'Rating (fr)',
        comments: 'Comments (fr)',
        date: 'Date (fr)',
        time: 'Time (fr)',
        id: 'id',
      },
    },
    TripHistory: {
      name: 'Trip History (fr)',
      fields: {
        tripId: 'Trip Id (fr)',
        userId: 'User Id (fr)',
        tripDate: 'Trip Date (fr)',
        destination: 'Destination (fr)',
        status: 'Status (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
